# Generated by Django 5.2.12 on 2026-04-04 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_no', models.CharField(max_length=20, unique=True)),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField(default=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'ordering': ['-departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_no', models.CharField(max_length=20)),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passenger_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be 10 digits')])),
                ('adhar_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Adhar number must be 12 digits')])),
                ('age', models.IntegerField()),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=50)),
                ('seat_no', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='base.flight')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
